{
  config,
  pkgs,
  lib,
  ...
}:
let
  hostname = config.var.hostname;
in
{
  home.packages =
    with pkgs;
    [
      adw-gtk3
      ani-cli
      calibre
      caligula
      catppuccin-cursors.latteLight
      gearlever
      hunspell
      hunspellDicts.en_US
      jdk
      mpv
      qt5.qtwayland
      qt6.qtwayland
      lazygit
      libreoffice-still
      libsForQt5.qt5ct
      hyprshot
      hyprpicker
      swappy
      imv
      wf-recorder
      wlr-randr
      wl-clipboard
      brightnessctl
      gnome-themes-extra
      libva
      dconf
      wayland-utils
      wayland-protocols
      glib
      direnv
      meson
      matugen
      upscaler
      cava
      cliphist
      btop
      xwayland-satellite
      nitch
      ntfs3g
      xdg-user-dirs
    ]
    ++ lib.optionals (hostname == "firelink") [
      #katawa-shoujo-re-engineered
      prismlauncher
      shadps4
      rpcs3
    ];
}
