keys:
  - &users:
    - &alec age190f2pt4z35cwe4spyq8yw4vehnhf70epgr8tktscadnx897ru3xsftw89l
  - &hosts:
    - &majula age1fxev0lnyakqfq9w82u66e4j3yjw00zgk5w0hvgr2m9mrex98hdcsml2wp5
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *alec
      - *majula
